# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cLogLikelihood <- function(Yvec, Xvec, DIMS, ALPHA, SS1) {
    .Call(`_dnc_cLogLikelihood`, Yvec, Xvec, DIMS, ALPHA, SS1)
}

cVBUpdate <- function(DIMS, Yvec, CC, GAMSTAR, A2STAR, B2STAR, B3STAR, EOmVec, muVec, SigVec, BI0G, BitbarVec, BithkVec, ER, ER2, AI2, BI2, NU, A3, B3, ES1, ES2, GAM) {
    .Call(`_dnc_cVBUpdate`, DIMS, Yvec, CC, GAMSTAR, A2STAR, B2STAR, B3STAR, EOmVec, muVec, SigVec, BI0G, BitbarVec, BithkVec, ER, ER2, AI2, BI2, NU, A3, B3, ES1, ES2, GAM)
}

cVBnoClust <- function(dims, Yvec, muVec, SigVec, A2STAR, B2STAR, B3STAR, EOmVec, A0, B0, A0STAR, B0STAR, AI2, BI2, A3, B3, ES1, ES2) {
    .Call(`_dnc_cVBnoClust`, dims, Yvec, muVec, SigVec, A2STAR, B2STAR, B3STAR, EOmVec, A0, B0, A0STAR, B0STAR, AI2, BI2, A3, B3, ES1, ES2)
}

cllikProj <- function(x, dims, ALPHA0, BETA0, UU, RR, TAU) {
    .Call(`_dnc_cllikProj`, x, dims, ALPHA0, BETA0, UU, RR, TAU)
}

cposteriorNoOmega <- function(dims, Yvec, XVec, RR, TAU, SS1, ALPHA, BETA, Z, UU, CC, GAMSTAR, A2STAR, B2STAR, B3STAR) {
    .Call(`_dnc_cposteriorNoOmega`, dims, Yvec, XVec, RR, TAU, SS1, ALPHA, BETA, Z, UU, CC, GAMSTAR, A2STAR, B2STAR, B3STAR)
}

csimulateData <- function(Xvec, dims, ALPHA, SS1) {
    .Call(`_dnc_csimulateData`, Xvec, dims, ALPHA, SS1)
}

drawMiss <- function(dims, Yvec, SS1, MISS, XVec, ALPHA) {
    .Call(`_dnc_drawMiss`, dims, Yvec, SS1, MISS, XVec, ALPHA)
}

drawS <- function(dims, Yvec, OmVec, XVec, ALPHA) {
    .Call(`_dnc_drawS`, dims, Yvec, OmVec, XVec, ALPHA)
}

drawTau <- function(dims, Xvec, RR, UU, Z) {
    .Call(`_dnc_drawTau`, dims, Xvec, RR, UU, Z)
}

drawU <- function(dims, TAU, RR, Xvec, Z) {
    .Call(`_dnc_drawU`, dims, TAU, RR, Xvec, Z)
}

drawXZar <- function(dims, XVec, Yvec, OmVec, SS1, ALPHA, TAU, RR, UU, ZZ, rnVec, BB, RNa, B3Star, CC) {
    .Call(`_dnc_drawXZar`, dims, XVec, Yvec, OmVec, SS1, ALPHA, TAU, RR, UU, ZZ, rnVec, BB, RNa, B3Star, CC)
}

